export const USER_FETCH = 'USER_FETCH';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';
export const USER_CREATE_FETCH = 'USER_CREATE_FETCH';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE';
export const USER_RESET = 'USER_RESET'